export const initialState = {
  loggingIn: false,
  loggedIn: false,
  fetchingUser: false,
  isAuthenticated: false,
  user: {},
  fetchingMeds: false,
  addingMed: false,
  editingMed: false,
  deletingMed: false,
  meds: [],
  activeMeds: [],
  inactiveMeds: [],
  med: {},
  fetchingDiary: false,
  addingDiary: false,
  editingDiary: false,
  deletingDiary: false,
  diary: [],
  fetchingRems: false,
  addingRems: false,
  rems: [],
  filteredRems: [],
  error: null
};